services:
  app:
    image: ghcr.io/harishdeivanayagam/rowfill
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/rowfill
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - SMTP_HOST=smtpout.secureserver.net  # your smtp host
      - SMTP_PORT=465  # your smtp port
      - SMTP_SECURE=true
      - SMTP_USER=user@example.com  # your smtp username
      - SMTP_PASS=dummy_password  # your smtp password
      - SMTP_FROM=noreply@example.com  # your from email
      - JWT_SECRET=your_jwt_secret_here  # your jwt secret
      - OPENAI_API_KEY=your_openai_key_here  # your openai api key
      - AWS_STORAGE_BUCKET_NAME=rowfill  # bucket will be created automatically
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_ACCESS_KEY_ID=minioadmin
      - AWS_S3_SECRET_ACCESS_KEY=minioadmin
      - NODE_ENV=production
      - WEAVIATE_LOCAL_URL=weaviate:8080
    depends_on:
      - postgres
      - redis
      - weaviate
      - minio
    command: >
      sh -c "pnpx prisma migrate deploy &&
             pnpm start:app"
    networks:
      - app-network

  cron:
    image: ghcr.io/harishdeivanayagam/rowfill
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/rowfill
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - SMTP_HOST=smtpout.secureserver.net  # your smtp host
      - SMTP_PORT=465  # your smtp port
      - SMTP_SECURE=true
      - SMTP_USER=user@example.com  # your smtp username
      - SMTP_PASS=dummy_password  # your smtp password
      - SMTP_FROM=noreply@example.com  # your from email
      - JWT_SECRET=your_jwt_secret_here  # your jwt secret
      - OPENAI_API_KEY=your_openai_key_here  # your openai api key
      - AWS_STORAGE_BUCKET_NAME=rowfill  # bucket will be created automatically
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_ACCESS_KEY_ID=minioadmin
      - AWS_S3_SECRET_ACCESS_KEY=minioadmin
      - NODE_ENV=production
      - WEAVIATE_LOCAL_URL=weaviate:8080
    depends_on:
      - postgres
      - redis
      - weaviate
      - minio
      - app
    command: pnpm start:cron
    networks:
      - app-network

  worker:
    image: ghcr.io/harishdeivanayagam/rowfill
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/rowfill
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - SMTP_HOST=smtpout.secureserver.net  # your smtp host
      - SMTP_PORT=465  # your smtp port
      - SMTP_SECURE=true
      - SMTP_USER=user@example.com  # your smtp username
      - SMTP_PASS=dummy_password  # your smtp password
      - SMTP_FROM=noreply@example.com  # your from email
      - JWT_SECRET=your_jwt_secret_here  # your jwt secret
      - OPENAI_API_KEY=your_openai_key_here  # your openai api key
      - AWS_STORAGE_BUCKET_NAME=rowfill  # bucket will be created automatically
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_ACCESS_KEY_ID=minioadmin
      - AWS_S3_SECRET_ACCESS_KEY=minioadmin
      - NODE_ENV=production
      - WEAVIATE_LOCAL_URL=weaviate:8080
    depends_on:
      - postgres
      - redis
      - weaviate
      - minio
      - app
    command: pnpm start:worker
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rowfill
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network


  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network


  weaviate:
    image: semitechnologies/weaviate:1.28.3
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - CLUSTER_HOSTNAME=node1
      - CLUSTER_GOSSIP_BIND_PORT=0
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - app-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_URL=https://bucket.server.com # Your server URL
      - MINIO_DOMAIN=bucket.server.com # For Virtual Host Style S3
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  weaviate_data:
  minio_data:

networks:
  app-network:
    driver: bridge
