name: App Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_PAT }}

      - name: Build API Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/harishdeivanayagam/rowfill